---
# role: journald
# file: tasks/main.yml

- name: JOURNALD | Configure journal storage and forwarding
  become: true
  become_user: root
  ansible.builtin.template:
    src: etc/systemd/journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart journald

- name: JOURNALD | Enable and start the journal service
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    enabled: true
    state: started
