---
# role: journald
# file: tasks/remote.yml

- name: JOURNALD | Create the remote journal directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ journald_remote_directory }}"
    state: directory
    owner: systemd-journal-remote
    group: systemd-journal-remote
    mode: '0750'

- name: JOURNALD | Create journal receiver unit override directories
  become: true
  become_user: root
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ __journald_unit }}.d"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - systemd-journal-remote.service
    - systemd-journal-remote.socket
  loop_control:
    loop_var: __journald_unit

- name: JOURNALD | Configure received journal storage
  become: true
  become_user: root
  ansible.builtin.template:
    src: etc/systemd/journal-remote.conf.j2
    dest: /etc/systemd/journal-remote.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart journal receiver

- name: JOURNALD | Configure journal receiver credentials and output
  become: true
  become_user: root
  ansible.builtin.template:
    src: etc/systemd/system/journal-remote.service.conf.j2
    dest: /etc/systemd/system/systemd-journal-remote.service.d/50-ansible.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - reload journal transport units
    - restart journal receiver

- name: JOURNALD | Configure the journal receiver listener
  become: true
  become_user: root
  ansible.builtin.template:
    src: etc/systemd/system/journal-remote.socket.conf.j2
    dest: /etc/systemd/system/systemd-journal-remote.socket.d/50-ansible.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - reload journal transport units
    - restart journal receiver socket
    - restart journal receiver
