---
# role: journald
# file: handlers/main.yml

- name: JOURNALD | Restart the journal service
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    state: restarted
  listen: restart journald

- name: JOURNALD | Apply the configured persistent storage mode
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: systemd-journal-flush.service
    state: restarted
  listen: restart journald
