---
# role: journald
# file: molecule/resources/playbooks/prepare.yml

- name: JOURNALD | Wait for test containers
  hosts: all
  gather_facts: false
  tasks:
    - name: JOURNALD | Wait for Ansible connectivity
      ansible.builtin.wait_for_connection:
        timeout: 60
