---
# role: journald
# file: molecule/resources/playbooks/verify.yml

- name: JOURNALD | Verify persistent journal storage
  hosts: all
  gather_facts: false
  tasks:
    - name: JOURNALD | Verify persisted messages and default priority handling
      ansible.builtin.import_tasks: ../tasks/verify_journal.yml
      vars:
        __journald_expected_directory: /var/log/journal
        __journald_expected_messages: [debug, warning]
